"""Add is_soft_expire column with default and create expired_links table

Revision ID: 2c2fa953c6f1
Revises: 8e3a32eb3061
Create Date: 2025-03-30 00:34:22.808688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '2c2fa953c6f1'
down_revision: Union[str, None] = '8e3a32eb3061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expired_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.Column('original_url', sa.Text(), nullable=False),
    sa.Column('short_code', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_click_at', sa.DateTime(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('is_soft_expire', sa.Boolean(), nullable=False, server_default=sa.sql.expression.true()),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('links', sa.Column('is_soft_expire',
                                     sa.Boolean(),
                                     nullable=False,
                                     server_default=sa.sql.expression.true()))

    op.alter_column('links', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('links', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('links', 'is_soft_expire')
    op.drop_table('expired_links')
    # ### end Alembic commands ###
